### PR TITLE
#157738496 Created the sign up page.

### PR DESCRIPTION
**Pull request by RuthNjeri**
**What does this PR do?**
Have a complete frontend design of the sign-up page.

**Description of tasks to be completed**
Have a form on the page that the user can enter an email, username and password to create an account.

**How should this be manually tested?**
Clone or download the repo. Navigate to the directory called UI and open the signIn.html file on any browser such as Chrome or FireFox.

**Any background context you want to provide?**
No

**What are the relevant Pivotal Tracker Stories?**
#157738496

**Screenshot**
image

### CODE REVIEW

**Comment by asamisellah** [comment]
I think your PR is well done. The branch has no conflicts. I would suggest adding screenshots where possible to make it easier for others to review your pages.
Kind regard

**Comment by denniswanjiru** [comment]
Well structured PR and detailed. Good job

**Comment by denniswanjiru** [comment]
Remember to change the base branch to develop before merging

**Comment by RuthNjeri** [comment]
@asamisellah Thank you. Screenshots have been added!

**Comment by RuthNjeri** [comment]
@DennisWanjiru The base branch has been changed! Thanks for the feedback.

**Pull request merged**
